
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    pull_policy: never
    container_name: mariadb
    hostname: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
    secrets:
      - source: db_password
        mode: 0444
      - source: db_root_password
        mode: 0444
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-P", "3306"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - intra

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    pull_policy: never
    container_name: wordpress
    hostname: wordpress
    restart: always
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - source: db_password
      - source: credentials
      - source: wp_admin_password
      - source: wp_user_password
    networks:
      - intra
  nginx:
    build: ./requirements/nginx
    image: nginx
    pull_policy: never
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - intra

  # BONUS SERVICES
  redis:
    build: ./requirements/bonus/redis
    image: redis
    pull_policy: never
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - intra

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    pull_policy: never
    container_name: ftp
    hostname: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    secrets:
      - source: ftp_password
    networks:
      - intra

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    pull_policy: never
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - intra

  website:
    build: ./requirements/bonus/website
    image: website
    pull_policy: never
    container_name: website
    hostname: website
    restart: always
    ports:
      - "5000:5000"
    networks:
      - intra

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stdi-pum/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stdi-pum/data/wordpress

networks:
  intra:
    name: inceptional
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
